# Generated by Django 5.2.9 on 2025-12-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ime akorda', max_length=150)),
                ('type', models.TextField(help_text='Upisite tip akorda', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Opis akorda', max_length=750, null=True)),
                ('picture_url', models.CharField(blank=True, max_length=750, null=True)),
            ],
        ),
    ]
