# Generated by Django 5.2.9 on 2025-12-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ime akorda', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Opis akorda', max_length=750, null=True)),
                ('picture_url', models.CharField(blank=True, max_length=750, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chord',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='chord',
            name='scheme_url',
            field=models.CharField(blank=True, help_text='Putanja do sheme akorda', max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='chord',
            name='symbol',
            field=models.TextField(blank=True, help_text='Simbol akorda', max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='chord',
            name='name',
            field=models.CharField(help_text='Ime akorda', max_length=15),
        ),
        migrations.AlterField(
            model_name='chord',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='chords.chordtype'),
        ),
    ]
