# Generated by Django 5.2.9 on 2025-12-04 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0002_chordtype_remove_chord_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chord',
            name='scheme_url',
        ),
        migrations.RemoveField(
            model_name='chordtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chordtype',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='chord',
            name='schema_url',
            field=models.CharField(blank=True, help_text='Putanja do sheme akorda', max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='chord',
            name='name',
            field=models.CharField(help_text='Naziv akorda', max_length=15),
        ),
        migrations.AlterField(
            model_name='chord',
            name='symbol',
            field=models.CharField(blank=True, help_text='Simbol akorda', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='chord',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='chords.chordtype'),
        ),
        migrations.AlterField(
            model_name='chordtype',
            name='name',
            field=models.CharField(help_text='Tip akorda', max_length=150),
        ),
    ]
