# Generated by Django 5.2.9 on 2025-12-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0003_remove_chord_scheme_url_remove_chordtype_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chord',
            old_name='schema_url',
            new_name='scheme_url',
        ),
    ]
